AWSTemplateFormatVersion: 2010-09-09
Description: Dynamic Pricing - DevOps - Network
  Network hub between AWS Pricing to Volaris Network
  Deploy of Transit Gateway, CustomerGateway and VPN Site-To-Site
Parameters: 
  Environment:
    Type: String
    Default: 'dev'
  VolCustomGatewayIP:
    Type: String
    Default: '209.249.149.18'
Resources: 
  PricingNetworkHubTGW:
    Type: AWS::EC2::TransitGateway
    Properties:
      AmazonSideAsn: 64512
      Description: "Vol Pricing TGW Network Hub to Volaris Network"
      AutoAcceptSharedAttachments: "disable"
      DefaultRouteTableAssociation: "enable"
      DnsSupport: "enable"
      VpnEcmpSupport: "enable"
      Tags:
        - Key: Name
          Value: !Sub 'VolPricingNTWHub-${Environment}-tgw'
        - Key: Company
          Value: vol
        - Key: Department
          Value: 'com'
        - Key: Project
          Value: 'ntw'
        - Key: Environment
          Value: !Ref Environment
        - Key: DevOpsTeam
          Value: 'comoptdevops'
        - Key: Owner
          Value: 'luis.calderon'
        - Key: Domain
          Value: 'rm'
        - Key: SubDomain
          Value: 'prc'
        - Key: CostAllocation
          Value: 'com-rm-vpchub'
        - Key: Component
          Value: ntwhub
  VolOneNeckCG:
    Type: AWS::EC2::CustomerGateway
    Properties:
      BgpAsn: 65000
      IpAddress: !Ref VolCustomGatewayIP
      Type: ipsec.1
      Tags:
        - Key: Company
          Value: vol
        - Key: Department
          Value: 'com'
        - Key: Project
          Value: 'ntw'
        - Key: Environment
          Value: !Ref Environment
        - Key: DevOpsTeam
          Value: 'comoptdevops'
        - Key: Owner
          Value: 'luis.calderon'
        - Key: Domain
          Value: 'rm'
        - Key: SubDomain
          Value: 'prc'
        - Key: CostAllocation
          Value: 'com-rm-vpchub'
        - Key: Component
          Value: ntwhub
  PricingVPNCon:
    Type: AWS::EC2::VPNConnection
    Properties: 
      CustomerGatewayId: !Ref VolOneNeckCG
      StaticRoutesOnly: true
      Tags: 
        - Key: Name
          Value: !Sub 'PricingVolarisVPN-${Environment}-vpnx'
        - Key: Company
          Value: vol
        - Key: Department
          Value: 'com'
        - Key: Project
          Value: 'ntw'
        - Key: Environment
          Value: !Ref Environment
        - Key: DevOpsTeam
          Value: 'comoptdevops'
        - Key: Owner
          Value: 'luis.calderon'
        - Key: Domain
          Value: 'rm'
        - Key: SubDomain
          Value: 'prc'
        - Key: CostAllocation
          Value: 'com-rm-vpchub'
        - Key: Component
          Value: ntwhub
      TransitGatewayId: !Ref PricingNetworkHubTGW
      Type: ipsec.1


