AWSTemplateFormatVersion: 2010-09-09
Description: Dynamic Pricing - DevOps - Network
Parameters: 
  Environment:
    Type: String
    Default: 'dev'
  NavPrivCIDR:
    Type: String
    Default: '10.108.0.0/16'
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'
  NavPubCIDR:
    Type: String
    Default: '10.107.0.0/16'
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'
  ProjectCIDR:
    Type: String
    Default: '10.106.0.0/16'
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'

Resources: 
  NavitairePrivateVPC:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: !Ref NavPrivCIDR
      EnableDnsHostnames: True
      EnableDnsSupport: True
      Tags: 
        - Key: "Name"
          Value: "VoiPricingNavitairePrivate-vpc"
  NPODSConSubNet1:
    Type: AWS::EC2::Subnet
    DependsOn: NavitairePrivateVPC
    Properties:
      VpcId:
        Ref: NavitairePrivateVPC
      CidrBlock: !Select [ 0, !Cidr [ !GetAtt NavitairePrivateVPC.CidrBlock, 6, 8]]
      AvailabilityZone: !Select [0, Fn::GetAZs: !Ref 'AWS::Region']
      Tags:
        - Key: Name
          Value: "ODSConnSubN1"
        - Key: Env
          Value: !Ref Environment
  NPODSConSubNet2:
    Type: AWS::EC2::Subnet
    DependsOn: NavitairePrivateVPC
    Properties:
      VpcId:
        Ref: NavitairePrivateVPC
      CidrBlock: !Select [ 1, !Cidr [ !GetAtt NavitairePrivateVPC.CidrBlock, 6, 8]]
      AvailabilityZone: !Select [1, Fn::GetAZs: !Ref 'AWS::Region']
      Tags:
        - Key: Name
          Value: "ODSConnSubN2"
        - Key: Env
          Value: !Ref Environment
  NPODSConSubNet3:
    Type: AWS::EC2::Subnet
    DependsOn: NavitairePrivateVPC
    Properties:
      VpcId:
        Ref: NavitairePrivateVPC
      CidrBlock: !Select [ 2, !Cidr [ !GetAtt NavitairePrivateVPC.CidrBlock, 6, 8]]
      AvailabilityZone: !Select [2, Fn::GetAZs: !Ref 'AWS::Region']
      Tags:
        - Key: Name
          Value: "ODSConnSubN3"
        - Key: Env
          Value: !Ref Environment
  NavitairePublicVPC:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: !Ref NavPubCIDR
      EnableDnsHostnames: True
      EnableDnsSupport: True
      Tags: 
        - Key: "Name"
          Value: "VoiPricingNavitairePublic-vpc"
  ProjectVPC:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: !Ref ProjectCIDR
      EnableDnsHostnames: True
      EnableDnsSupport: True
      Tags: 
        - Key: "Name"
          Value: "VoiPricing-vpc"
