AWSTemplateFormatVersion: 2010-09-09
Description: Dynamic Pricing - DevOps - Network
Parameters: 
  Environment:
    Type: String
    Default: 'dev'
  NavitaireCIDR:
    Type: String
    Default: '149.122.50.0/24'
  TGRegion:
    Type: String
    Default: us-east-1
  TGatewayId:
    Type: String
    Default: tgw-0198c3591361cf885
  TGAccountId:
    Type: String
    Default: '198251194805'
  NavPrivCIDR:
    Type: String
    Default: '10.108.0.0/16'
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'
  NavPubCIDR:
    Type: String
    Default: '10.107.0.0/16'
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'
  ProjectCIDR:
    Type: String
    Default: '10.106.0.0/16'
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'

Resources: 
  NavitairePrivateVPC:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: !Ref NavPrivCIDR
      EnableDnsHostnames: True
      EnableDnsSupport: True
      Tags: 
        - Key: "Name"
          Value: "VolPrcNavPrv-vpc"
  NavitairePrivateRT:
    Type: AWS::EC2::RouteTable
    DependsOn: NavitairePrivateVPC
    Properties:
      VpcId: !Ref NavitairePrivateVPC
      Tags:
        - Key: Name
          Value: "VolPrcNavPrv-rt"
        - Key: Env
          Value: !Ref Environment
  NPODSConSubNet1:
    Type: AWS::EC2::Subnet
    DependsOn: NavitairePrivateVPC
    Properties:
      VpcId:
        Ref: NavitairePrivateVPC
      CidrBlock: !Select [ 0, !Cidr [ !GetAtt NavitairePrivateVPC.CidrBlock, 6, 8]]
      AvailabilityZone: !Select [0, Fn::GetAZs: !Ref 'AWS::Region']
      Tags:
        - Key: Name
          Value: "NavDotRezSubN1"
        - Key: Env
          Value: !Ref Environment
  NPODSConSubNet2:
    Type: AWS::EC2::Subnet
    DependsOn: NavitairePrivateVPC
    Properties:
      VpcId:
        Ref: NavitairePrivateVPC
      CidrBlock: !Select [ 1, !Cidr [ !GetAtt NavitairePrivateVPC.CidrBlock, 6, 8]]
      AvailabilityZone: !Select [1, Fn::GetAZs: !Ref 'AWS::Region']
      Tags:
        - Key: Name
          Value: "NavDotRezSubN2"
        - Key: Env
          Value: !Ref Environment
  NPODSConSubNet3:
    Type: AWS::EC2::Subnet
    DependsOn: NavitairePrivateVPC
    Properties:
      VpcId:
        Ref: NavitairePrivateVPC
      CidrBlock: !Select [ 2, !Cidr [ !GetAtt NavitairePrivateVPC.CidrBlock, 6, 8]]
      AvailabilityZone: !Select [2, Fn::GetAZs: !Ref 'AWS::Region']
      Tags:
        - Key: Name
          Value: "NavDotRezSubN3"
        - Key: Env
          Value: !Ref Environment
  NPNewSkiesSubNet1:
    Type: AWS::EC2::Subnet
    DependsOn: NavitairePrivateVPC
    Properties:
      VpcId:
        Ref: NavitairePrivateVPC
      CidrBlock: !Select [ 3, !Cidr [ !GetAtt NavitairePrivateVPC.CidrBlock, 6, 8]]
      AvailabilityZone: !Select [0, Fn::GetAZs: !Ref 'AWS::Region']
      Tags:
        - Key: Name
          Value: "NewSkiesSubN1"
        - Key: Env
          Value: !Ref Environment
  NPNewSkiesSubNet2:
    Type: AWS::EC2::Subnet
    DependsOn: NavitairePrivateVPC
    Properties:
      VpcId:
        Ref: NavitairePrivateVPC
      CidrBlock: !Select [ 4, !Cidr [ !GetAtt NavitairePrivateVPC.CidrBlock, 6, 8]]
      AvailabilityZone: !Select [1, Fn::GetAZs: !Ref 'AWS::Region']
      Tags:
        - Key: Name
          Value: "NewSkiesSubN2"
        - Key: Env
          Value: !Ref Environment
  NPNewSkiesSubNet3:
    Type: AWS::EC2::Subnet
    DependsOn: NavitairePrivateVPC
    Properties:
      VpcId:
        Ref: NavitairePrivateVPC
      CidrBlock: !Select [ 5, !Cidr [ !GetAtt NavitairePrivateVPC.CidrBlock, 6, 8]]
      AvailabilityZone: !Select [2, Fn::GetAZs: !Ref 'AWS::Region']
      Tags:
        - Key: Name
          Value: "NewSkiesSubN3"
        - Key: Env
          Value: !Ref Environment
  NPODSConSubNet1RTAss:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: NPODSConSubNet1
      RouteTableId:
        Ref: NavitairePrivateRT
  NPODSConSubNet2RTAss:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: NPODSConSubNet2
      RouteTableId:
        Ref: NavitairePrivateRT
  NPODSConSubNet3RTAss:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: NPODSConSubNet3
      RouteTableId:
        Ref: NavitairePrivateRT
  NPNewSkiesSubNet1RTAss:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: NPNewSkiesSubNet1
      RouteTableId:
        Ref: NavitairePrivateRT
  NPNewSkiesSubNet2RTAss:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: NPNewSkiesSubNet2
      RouteTableId:
        Ref: NavitairePrivateRT
  NPNewSkiesSubNet3RTAss:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: NPNewSkiesSubNet3
      RouteTableId:
        Ref: NavitairePrivateRT
  NavitairePrivateTGW:
    Type: "AWS::EC2::TransitGateway"
    Properties:
      AmazonSideAsn: 65000
      Description: "TGW Dev Integration"
      AutoAcceptSharedAttachments: "disable"
      DefaultRouteTableAssociation: "enable"
      DnsSupport: "enable"
      VpnEcmpSupport: "enable"
      Tags:
        - Key: Env
          Value: !Ref Environment
        - Key: Name
          Value: !Sub 'VolITNetwork-${Environment}-tgw'
  NPTGWPeerAttach:
    Type: AWS::EC2::TransitGatewayPeeringAttachment
    Properties: 
      PeerAccountId: !Ref TGAccountId
      PeerRegion: !Ref TGRegion
      PeerTransitGatewayId: !Ref TGatewayId
      TransitGatewayId: !Ref NavitairePrivateTGW
      Tags: 
        - Key: Env
          Value: !Ref Environment
        - Key: Name
          Value: !Sub 'VolITNav-${Environment}-tgwa'
  NPTGWVPCAttach:
    Type: AWS::EC2::TransitGatewayAttachment
    Properties: 
      SubnetIds: 
        - !Ref NPODSConSubNet1
        - !Ref NPODSConSubNet2
        - !Ref NPNewSkiesSubNet3
      Tags: 
        - Key: Env
          Value: !Ref Environment
        - Key: Name
          Value: !Sub 'VolPrcNavPriv-${Environment}-vpc'
      TransitGatewayId: !Ref NavitairePrivateTGW
      VpcId: !Ref NavitairePrivateVPC
  NPS3Endpoint:
    Type: AWS::EC2::VPCEndpoint
    DependsOn: NavitairePrivateRT
    Properties:
      RouteTableIds: 
        - !Ref NavitairePrivateRT
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.s3'
      VpcEndpointType: Gateway
      VpcId: !Ref NavitairePrivateVPC
  NPTGWRoute:
    Type: AWS::EC2::Route
    DependsOn: NPTGWVPCAttach
    Properties:
       RouteTableId:
         Ref: NavitairePrivateRT
       DestinationCidrBlock: !Ref NavitaireCIDR
       TransitGatewayId:
         Ref: NavitairePrivateTGW

  NavitairePublicVPC:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: !Ref NavPubCIDR
      EnableDnsHostnames: True
      EnableDnsSupport: True
      Tags: 
        - Key: "Name"
          Value: "VolPrcNavPub-vpc"
  NPubDotRezSubNet1:
    Type: AWS::EC2::Subnet
    DependsOn: NavitairePublicVPC
    Properties:
      VpcId:
        Ref: NavitairePublicVPC
      CidrBlock: !Select [ 0, !Cidr [ !GetAtt NavitairePublicVPC.CidrBlock, 6, 8]]
      AvailabilityZone: !Select [0, Fn::GetAZs: !Ref 'AWS::Region']
      Tags:
        - Key: Name
          Value: "NavDotRezSubN1"
        - Key: Env
          Value: !Ref Environment
  NPubDotRezSubNet2:
    Type: AWS::EC2::Subnet
    DependsOn: NavitairePublicVPC
    Properties:
      VpcId:
        Ref: NavitairePublicVPC
      CidrBlock: !Select [ 1, !Cidr [ !GetAtt NavitairePublicVPC.CidrBlock, 6, 8]]
      AvailabilityZone: !Select [1, Fn::GetAZs: !Ref 'AWS::Region']
      Tags:
        - Key: Name
          Value: "NavDotRezSubN2"
        - Key: Env
          Value: !Ref Environment
  NPubDotRezSubNet3:
    Type: AWS::EC2::Subnet
    DependsOn: NavitairePublicVPC
    Properties:
      VpcId:
        Ref: NavitairePublicVPC
      CidrBlock: !Select [ 2, !Cidr [ !GetAtt NavitairePublicVPC.CidrBlock, 6, 8]]
      AvailabilityZone: !Select [2, Fn::GetAZs: !Ref 'AWS::Region']
      Tags:
        - Key: Name
          Value: "NavDotRezSubN3"
        - Key: Env
          Value: !Ref Environment
  NavPubRT:
    Type: AWS::EC2::RouteTable
    DependsOn: NavitairePublicVPC
    Properties:
      VpcId: !Ref NavitairePublicVPC
      Tags:
        - Key: Name
          Value: "VolPrcNavPub-rt"
        - Key: Env
          Value: !Ref Environment
  NPubS3Endpoint:
    Type: AWS::EC2::VPCEndpoint
    DependsOn: NavPubRT
    Properties:
      RouteTableIds: 
        - !Ref NavPubRT
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.s3'
      VpcEndpointType: Gateway
      VpcId: !Ref NavitairePublicVPC
  PrcNavPubPeerCon:
    Type: AWS::EC2::VPCPeeringConnection
    Properties:
      PeerVpcId: !Ref ProjectVPC
      VpcId: !Ref NavitairePublicVPC
      Tags: 
        - Key: "Name"
          Value: "VolPricingNavPub-pcx"
  NPrvPeerConRT:
    Type: AWS::EC2::Route
    DependsOn: PrcNavPubPeerCon
    Properties:
       RouteTableId:
         Ref: NavPubRT
       DestinationCidrBlock: "0.0.0.0/16"
       VpcPeeringConnectionId:
         Ref: PrcNavPubPeerCon
  ProjectVPC:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: !Ref ProjectCIDR
      EnableDnsHostnames: True
      EnableDnsSupport: True
      Tags: 
        - Key: "Name"
          Value: "VolPricing-vpc"
  PrcPubRT:
    Type: AWS::EC2::RouteTable
    DependsOn: ProjectVPC
    Properties:
      VpcId: !Ref ProjectVPC
      Tags:
        - Key: Name
          Value: "VolPrcPub-rt"
        - Key: Env
          Value: !Ref Environment
  PrcPrvRT:
    Type: AWS::EC2::RouteTable
    DependsOn: ProjectVPC
    Properties:
      VpcId: !Ref ProjectVPC
      Tags:
        - Key: Name
          Value: "VolPrcPrv-rt"
        - Key: Env
          Value: !Ref Environment
  PrcPublicSubNet1:
    Type: AWS::EC2::Subnet
    DependsOn: ProjectVPC
    Properties:
      VpcId:
        Ref: ProjectVPC
      CidrBlock: !Select [ 0, !Cidr [ !GetAtt ProjectVPC.CidrBlock, 15, 8]]
      AvailabilityZone: !Select [0, Fn::GetAZs: !Ref 'AWS::Region']
      Tags:
        - Key: Name
          Value: "PrcPublicSub1"
        - Key: Env
          Value: !Ref Environment
  PrcPublicSubNet2:
    Type: AWS::EC2::Subnet
    DependsOn: ProjectVPC
    Properties:
      VpcId:
        Ref: ProjectVPC
      CidrBlock: !Select [ 1, !Cidr [ !GetAtt ProjectVPC.CidrBlock, 15, 8]]
      AvailabilityZone: !Select [1, Fn::GetAZs: !Ref 'AWS::Region']
      Tags:
        - Key: Name
          Value: "PrcPublicSub2"
        - Key: Env
          Value: !Ref Environment
  PrcPublicSubNet3:
    Type: AWS::EC2::Subnet
    DependsOn: ProjectVPC
    Properties:
      VpcId:
        Ref: ProjectVPC
      CidrBlock: !Select [ 2, !Cidr [ !GetAtt ProjectVPC.CidrBlock, 15, 8]]
      AvailabilityZone: !Select [2, Fn::GetAZs: !Ref 'AWS::Region']
      Tags:
        - Key: Name
          Value: "PrcPublicSub3"
        - Key: Env
          Value: !Ref Environment
  PrcDataWarehouseSubNet1:
    Type: AWS::EC2::Subnet
    DependsOn: ProjectVPC
    Properties:
      VpcId:
        Ref: ProjectVPC
      CidrBlock: !Select [ 3, !Cidr [ !GetAtt ProjectVPC.CidrBlock, 15, 8]]
      AvailabilityZone: !Select [0, Fn::GetAZs: !Ref 'AWS::Region']
      Tags:
        - Key: Name
          Value: "PrcDataWarehouseSub1"
        - Key: Env
          Value: !Ref Environment
  PrcDataWarehouseSubNet2:
    Type: AWS::EC2::Subnet
    DependsOn: ProjectVPC
    Properties:
      VpcId:
        Ref: ProjectVPC
      CidrBlock: !Select [ 4, !Cidr [ !GetAtt ProjectVPC.CidrBlock, 15, 8]]
      AvailabilityZone: !Select [1, Fn::GetAZs: !Ref 'AWS::Region']
      Tags:
        - Key: Name
          Value: "PrcDataWarehouseSub2"
        - Key: Env
          Value: !Ref Environment
  PrcDataWarehouseSubNet3:
    Type: AWS::EC2::Subnet
    DependsOn: ProjectVPC
    Properties:
      VpcId:
        Ref: ProjectVPC
      CidrBlock: !Select [ 5, !Cidr [ !GetAtt ProjectVPC.CidrBlock, 15, 8]]
      AvailabilityZone: !Select [2, Fn::GetAZs: !Ref 'AWS::Region']
      Tags:
        - Key: Name
          Value: "PrcPublicSub3"
        - Key: Env
          Value: !Ref Environment
  
 